# Week 05 – Boolean Masks (Deep Foundation)

## Focus:
Develop a strong conceptual and practical understanding of Boolean masks in pandas for multi-criteria experimental decision logic.

## Skills practiced:
- Creating single-condition Boolean masks
- Combining conditions using `&` (AND)
- Combining conditions using `|` (OR)
- Using `~` (NOT) to invert masks
- Understanding operator precedence and parentheses discipline
- Applying masks to filter DataFrames
- Creating decision columns (e.g., advance / drop logic)

## Biological context:
Simulating compound triage logic in high-throughput screening:
- Identifying active compounds (effect threshold)
- Filtering for safety (toxicity threshold)
- Combining multiple criteria for go / no-go decisions
- Encoding experimental prioritization into reproducible code

---

## Core Operators

| Symbol | Meaning | Description |
|--------|----------|------------|
| `&` | AND | True only if both conditions are True (row-wise) |
| `|` | OR | True if at least one condition is True (row-wise) |
| `~` | NOT | Flips True ↔ False in a Boolean mask |

---

## Rule Reminder

When using `&` or `|`, always wrap each condition in parentheses:

Correct:
```python
(df["effect"] > 20) & (df["toxicity"] < 50)

In [15]:
import pandas as pd

In [16]:
#--- Parameters/ example data (defined first) ---
compounds = ["A", "B", "C", "D"]
effect_values = [ 10, 35, 50, 15]
toxicity_values = [20, 60, 30, 10]

#--- Build Data Frames ---
df = pd. DataFrame({
    "compound": compounds, 
    "effect": effect_values, 
    "toxicity": toxicity_values 
})

df

  compound  effect  toxicity
0        A      10        20
1        B      35        60
2        C      50        30
3        D      15        10

In [17]:
#--- Thresholds (defined first) ---
effect_threshold = 20
toxicity_threshold = 50

In [18]:
#--- Single-condition masks ---
active_mask = df["effect"] > effect_threshold
safe_mask = df["toxicity"] < toxicity_threshold

active_mask, safe_mask

(0    False
 1     True
 2     True
 3    False
 Name: effect, dtype: bool,
 0     True
 1    False
 2     True
 3     True
 Name: toxicity, dtype: bool)

In [25]:
#--- Combined Mask ---
active_and_safe_mask = active_mask & safe_mask
active_and_safe_mask

0    False
1    False
2     True
3    False
dtype: bool

In [26]:
df["active"] = active_mask
df["safe"] = safe_mask
df["active_and_safe"] = active_and_safe_mask

df

  compound  effect  toxicity  active   safe  active_and_safe
0        A      10        20   False   True            False
1        B      35        60    True  False            False
2        C      50        30    True   True             True
3        D      15        10   False   True            False

In [28]:
df["decision"] = df["active_and_safe"].map({True: "Advance", False: "Drop"})
df

  compound  effect  toxicity  active   safe  active_and_safe decision
0        A      10        20   False   True            False     Drop
1        B      35        60    True  False            False     Drop
2        C      50        30    True   True             True  Advance
3        D      15        10   False   True            False     Drop