# Week 06 - Loading & Inspecting Screening Data

**Focus:** Loading real instrument data files into Python and performing first-pass QC inspection.

**Skills practiced:**
- Loading CSV files with `pd.read_csv()`
- Loading Excel files with `pd.read_excel()`
- Inspecting table structure with `.shape`, `.dtypes`, `.info()`
- Identifying missing values with `.isnull().sum()`
- Filtering to failed wells using masks

**Biological context:** Before any analysis, screening data must be inspected for failed wells, missing values, and data integrity. This mirrors the QC checks performed before calculating plate statistics in a real drug discovery workflow.

## 1. Import Libraries

In [1]:
# Load pandas for working with tabular data
import pandas as pd

## 2. Load Data Files

In [2]:
# Load plate reader CSV - one row per well, contains MBP ratio and viability readouts
df_plate = pd.read_csv("plate_reader_data.csv")

df_plate

   well_id  compound  dose_uM  MBP_ratio  viability_norm  plate_id  assay_date
0      B02      DMSO      0.0       0.08            1.00  Plate_01  2024-03-15
1      B03      DMSO      0.0       0.09            0.98  Plate_01  2024-03-15
2      B04      DMSO      0.0       0.07            1.02  Plate_01  2024-03-15
3      B05      DMSO      0.0       0.08            0.99  Plate_01  2024-03-15
4      B06  Pos_Ctrl     10.0       0.72            0.95  Plate_01  2024-03-15
5      B07  Pos_Ctrl     10.0       0.75            0.97  Plate_01  2024-03-15
6      B08  Pos_Ctrl     10.0       0.70            0.93  Plate_01  2024-03-15
7      B09  Pos_Ctrl     10.0       0.73            0.96  Plate_01  2024-03-15
8      C02   Cpd_001      0.1       0.09            0.99  Plate_01  2024-03-15
9      C03   Cpd_001      1.0       0.18            0.97  Plate_01  2024-03-15
10     C04   Cpd_001     10.0       0.55            0.88  Plate_01  2024-03-15
11     D02   Cpd_002      0.1       0.08            1.01  Plate_01  2024-03-15
12     D03   Cpd_002      1.0       0.09            0.99  Plate_01  2024-03-15
13     D04   Cpd_002     10.0       0.10            0.95  Plate_01  2024-03-15
14     E02   Cpd_003      0.1       0.10            0.98  Plate_01  2024-03-15
15     E03   Cpd_003      1.0       0.35            0.96  Plate_01  2024-03-15
16     E04   Cpd_003     10.0       0.68            0.45  Plate_01  2024-03-15
17     F02   Cpd_004      0.1       0.07            0.97  Plate_01  2024-03-15
18     F03   Cpd_004      1.0       0.08            0.98  Plate_01  2024-03-15
19     F04   Cpd_004     10.0        NaN             NaN  Plate_01  2024-03-15
20     G02   Cpd_005      0.1       0.09            1.00  Plate_01  2024-03-15
21     G03   Cpd_005      1.0       0.12            0.99  Plate_01  2024-03-15
22     G04   Cpd_005     10.0       0.15            0.97  Plate_01  2024-03-15
23     H02   Cpd_006      0.1       0.08            0.98  Plate_01  2024-03-15
24     H03   Cpd_006      1.0       0.08            1.01  Plate_01  2024-03-15
25     H04   Cpd_006     10.0       0.09            0.99  Plate_01  2024-03-15
26     I02   Cpd_007      0.1       0.11            0.99  Plate_01  2024-03-15
27     I03   Cpd_007      1.0       0.45            0.97  Plate_01  2024-03-15
28     I04   Cpd_007     10.0       0.71            0.91  Plate_01  2024-03-15
29     J02   Cpd_008      0.1       0.09            1.02  Plate_01  2024-03-15
30     J03   Cpd_008      1.0       0.10            0.98  Plate_01  2024-03-15
31     J04   Cpd_008     10.0       0.82            0.93  Plate_01  2024-03-15

In [13]:
# Count missing values per column in each dataset
df_plate.isnull().sum()

well_id           0
compound          0
dose_uM           0
MBP_ratio         1
viability_norm    1
plate_id          0
assay_date        0
dtype: int64

In [10]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [14]:
# Load CellProfiler Excel export - one row per well, contains imaging metrics 
df_cellprofiler = pd.read_excel("cellprofiler_export.xlsx", sheet_name="Well_Data")

df_cellprofiler

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI
0,B02,DMSO,0.0,420.0,34.0,312.0,2105.0,Plate_01,2024-03-15,10x,CY3,DAPI
1,B03,DMSO,0.0,398.0,36.0,298.0,2089.0,Plate_01,2024-03-15,10x,CY3,DAPI
2,B04,DMSO,0.0,411.0,29.0,321.0,2118.0,Plate_01,2024-03-15,10x,CY3,DAPI
3,B05,DMSO,0.0,405.0,32.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI
4,B06,Pos_Ctrl,10.0,385.0,277.0,1842.0,2034.0,Plate_01,2024-03-15,10x,CY3,DAPI
5,B07,Pos_Ctrl,10.0,392.0,294.0,1910.0,2055.0,Plate_01,2024-03-15,10x,CY3,DAPI
6,B08,Pos_Ctrl,10.0,378.0,265.0,1798.0,2019.0,Plate_01,2024-03-15,10x,CY3,DAPI
7,B09,Pos_Ctrl,10.0,401.0,293.0,1876.0,2048.0,Plate_01,2024-03-15,10x,CY3,DAPI
8,C02,Cpd_001,0.1,415.0,37.0,315.0,2098.0,Plate_01,2024-03-15,10x,CY3,DAPI
9,C03,Cpd_001,1.0,408.0,73.0,580.0,2087.0,Plate_01,2024-03-15,10x,CY3,DAPI
10,C04,Cpd_001,10.0,399.0,219.0,1421.0,2071.0,Plate_01,2024-03-15,10x,CY3,DAPI
11,D02,Cpd_002,0.1,422.0,34.0,308.0,2112.0,Plate_01,2024-03-15,10x,CY3,DAPI
12,D03,Cpd_002,1.0,410.0,37.0,312.0,2095.0,Plate_01,2024-03-15,10x,CY3,DAPI
13,D04,Cpd_002,10.0,418.0,42.0,319.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
14,E02,Cpd_003,0.1,412.0,41.0,320.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI
15,E03,Cpd_003,1.0,405.0,142.0,890.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI
16,E04,Cpd_003,10.0,NaN,NaN,NaN,NaN,Plate_01,2024-03-15,10x,CY3,DAPI
17,F02,Cpd_004,0.1,418.0,29.0,301.0,2102.0,Plate_01,2024-03-15,10x,CY3,DAPI
18,F03,Cpd_004,1.0,412.0,33.0,310.0,2096.0,Plate_01,2024-03-15,10x,CY3,DAPI
19,F04,Cpd_004,10.0,NaN,NaN,NaN,NaN,Plate_01,2024-03-15,10x,CY3,DAPI
20,G02,Cpd_005,0.1,409.0,37.0,318.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
21,G03,Cpd_005,1.0,415.0,50.0,402.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI
22,G04,Cpd_005,10.0,407.0,61.0,489.0,2101.0,Plate_01,2024-03-15,10x,CY3,DAPI
23,H02,Cpd_006,0.1,420.0,34.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI
24,H03,Cpd_006,1.0,416.0,33.0,309.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI
25,H04,Cpd_006,10.0,411.0,37.0,314.0,2085.0,Plate_01,2024-03-15,10x,CY3,DAPI
26,I02,Cpd_007,0.1,418.0,46.0,340.0,2103.0,Plate_01,2024-03-15,10x,CY3,DAPI
27,I03,Cpd_007,1.0,407.0,183.0,1102.0,2090.0,Plate_01,2024-03-15,10x,CY3,DAPI
28,I04,Cpd_007,10.0,395.0,281.0,1798.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI
29,J02,Cpd_008,0.1,412.0,37.0,311.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI
30,J03,Cpd_008,1.0,408.0,41.0,338.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI

## 3. Initial QC — Check for Missing Values

In [15]:
# Count missing values per column - CellProfiler data
df_cellprofiler.isnull().sum()

WellID                    0
Compound                  0
Dose_uM                   0
TotalCells_Count          2
MBP_Positive_Count        2
Mean_MBP_Intensity_AU     2
Mean_DAPI_Intensity_AU    2
Plate_ID                  0
Image_Date                0
Objective                 0
Channel_MBP               0
Channel_DAPI              0
dtype: int64

In [16]:
# Filter to failed wells - rows where TotalCells_Count is missing
failed_mask=df_cellprofiler["TotalCells_Count"].isnull()
df_cellprofiler[failed_mask]

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI
16,E04,Cpd_003,10.0,NaN,NaN,NaN,NaN,Plate_01,2024-03-15,10x,CY3,DAPI
19,F04,Cpd_004,10.0,NaN,NaN,NaN,NaN,Plate_01,2024-03-15,10x,CY3,DAPI

## 4. Remove Failed Wells — Create Clean Dataset

In [25]:
# Exclude failed wells — keep only rows where TotalCells_Count is not missing
# ~ flips the mask: True becomes False and False becomes True
# Original df_cellprofiler is preserved; df_clean is used for downstream analysis
clean_mask = ~ failed_mask
df_clean = df_cellprofiler[clean_mask]

df_clean = df_cellprofiler[clean_mask].copy()
df_clean

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI
0,B02,DMSO,0.0,420.0,34.0,312.0,2105.0,Plate_01,2024-03-15,10x,CY3,DAPI
1,B03,DMSO,0.0,398.0,36.0,298.0,2089.0,Plate_01,2024-03-15,10x,CY3,DAPI
2,B04,DMSO,0.0,411.0,29.0,321.0,2118.0,Plate_01,2024-03-15,10x,CY3,DAPI
3,B05,DMSO,0.0,405.0,32.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI
4,B06,Pos_Ctrl,10.0,385.0,277.0,1842.0,2034.0,Plate_01,2024-03-15,10x,CY3,DAPI
5,B07,Pos_Ctrl,10.0,392.0,294.0,1910.0,2055.0,Plate_01,2024-03-15,10x,CY3,DAPI
6,B08,Pos_Ctrl,10.0,378.0,265.0,1798.0,2019.0,Plate_01,2024-03-15,10x,CY3,DAPI
7,B09,Pos_Ctrl,10.0,401.0,293.0,1876.0,2048.0,Plate_01,2024-03-15,10x,CY3,DAPI
8,C02,Cpd_001,0.1,415.0,37.0,315.0,2098.0,Plate_01,2024-03-15,10x,CY3,DAPI
9,C03,Cpd_001,1.0,408.0,73.0,580.0,2087.0,Plate_01,2024-03-15,10x,CY3,DAPI
10,C04,Cpd_001,10.0,399.0,219.0,1421.0,2071.0,Plate_01,2024-03-15,10x,CY3,DAPI
11,D02,Cpd_002,0.1,422.0,34.0,308.0,2112.0,Plate_01,2024-03-15,10x,CY3,DAPI
12,D03,Cpd_002,1.0,410.0,37.0,312.0,2095.0,Plate_01,2024-03-15,10x,CY3,DAPI
13,D04,Cpd_002,10.0,418.0,42.0,319.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
14,E02,Cpd_003,0.1,412.0,41.0,320.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI
15,E03,Cpd_003,1.0,405.0,142.0,890.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI
17,F02,Cpd_004,0.1,418.0,29.0,301.0,2102.0,Plate_01,2024-03-15,10x,CY3,DAPI
18,F03,Cpd_004,1.0,412.0,33.0,310.0,2096.0,Plate_01,2024-03-15,10x,CY3,DAPI
20,G02,Cpd_005,0.1,409.0,37.0,318.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
21,G03,Cpd_005,1.0,415.0,50.0,402.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI
22,G04,Cpd_005,10.0,407.0,61.0,489.0,2101.0,Plate_01,2024-03-15,10x,CY3,DAPI
23,H02,Cpd_006,0.1,420.0,34.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI
24,H03,Cpd_006,1.0,416.0,33.0,309.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI
25,H04,Cpd_006,10.0,411.0,37.0,314.0,2085.0,Plate_01,2024-03-15,10x,CY3,DAPI
26,I02,Cpd_007,0.1,418.0,46.0,340.0,2103.0,Plate_01,2024-03-15,10x,CY3,DAPI
27,I03,Cpd_007,1.0,407.0,183.0,1102.0,2090.0,Plate_01,2024-03-15,10x,CY3,DAPI
28,I04,Cpd_007,10.0,395.0,281.0,1798.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI
29,J02,Cpd_008,0.1,412.0,37.0,311.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI
30,J03,Cpd_008,1.0,408.0,41.0,338.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI

In [26]:
df_clean["MBP_ratio"]=df_clean["MBP_Positive_Count"] / df_clean["TotalCells_Count"]

In [27]:
df_clean

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio
0,B02,DMSO,0.0,420.0,34.0,312.0,2105.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080952
1,B03,DMSO,0.0,398.0,36.0,298.0,2089.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090452
2,B04,DMSO,0.0,411.0,29.0,321.0,2118.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.070560
3,B05,DMSO,0.0,405.0,32.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.079012
4,B06,Pos_Ctrl,10.0,385.0,277.0,1842.0,2034.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.719481
5,B07,Pos_Ctrl,10.0,392.0,294.0,1910.0,2055.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.750000
6,B08,Pos_Ctrl,10.0,378.0,265.0,1798.0,2019.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.701058
7,B09,Pos_Ctrl,10.0,401.0,293.0,1876.0,2048.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.730673
8,C02,Cpd_001,0.1,415.0,37.0,315.0,2098.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.089157
9,C03,Cpd_001,1.0,408.0,73.0,580.0,2087.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.178922
10,C04,Cpd_001,10.0,399.0,219.0,1421.0,2071.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.548872
11,D02,Cpd_002,0.1,422.0,34.0,308.0,2112.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080569
12,D03,Cpd_002,1.0,410.0,37.0,312.0,2095.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090244
13,D04,Cpd_002,10.0,418.0,42.0,319.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.100478
14,E02,Cpd_003,0.1,412.0,41.0,320.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.099515
15,E03,Cpd_003,1.0,405.0,142.0,890.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.350617
17,F02,Cpd_004,0.1,418.0,29.0,301.0,2102.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.069378
18,F03,Cpd_004,1.0,412.0,33.0,310.0,2096.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080097
20,G02,Cpd_005,0.1,409.0,37.0,318.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090465
21,G03,Cpd_005,1.0,415.0,50.0,402.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.120482
22,G04,Cpd_005,10.0,407.0,61.0,489.0,2101.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.149877
23,H02,Cpd_006,0.1,420.0,34.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080952
24,H03,Cpd_006,1.0,416.0,33.0,309.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.079327
25,H04,Cpd_006,10.0,411.0,37.0,314.0,2085.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090024
26,I02,Cpd_007,0.1,418.0,46.0,340.0,2103.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.110048
27,I03,Cpd_007,1.0,407.0,183.0,1102.0,2090.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.449631
28,I04,Cpd_007,10.0,395.0,281.0,1798.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.711392
29,J02,Cpd_008,0.1,412.0,37.0,311.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.089806
30,J03,Cpd_008,1.0,408.0,41.0,338.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.100490
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.822055

In [30]:
DMSO_mask = df_clean["Compound"] == "DMSO" 

df_DMSO = df_clean[DMSO_mask]
df_DMSO

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio
0,B02,DMSO,0.0,420.0,34.0,312.0,2105.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080952
1,B03,DMSO,0.0,398.0,36.0,298.0,2089.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090452
2,B04,DMSO,0.0,411.0,29.0,321.0,2118.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.070560
3,B05,DMSO,0.0,405.0,32.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.079012

In [32]:
DMSO_avg = df_DMSO["MBP_ratio"].mean()
DMSO_avg

np.float64(0.08024414966088052)

In [34]:
df_clean["MBP_ratio_normalized"] = df_clean["MBP_ratio"] / DMSO_avg
df_clean

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio,MBP_ratio_normalized
0,B02,DMSO,0.0,420.0,34.0,312.0,2105.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080952,1.008826
1,B03,DMSO,0.0,398.0,36.0,298.0,2089.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090452,1.127213
2,B04,DMSO,0.0,411.0,29.0,321.0,2118.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.070560,0.879312
3,B05,DMSO,0.0,405.0,32.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.079012,0.984649
4,B06,Pos_Ctrl,10.0,385.0,277.0,1842.0,2034.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.719481,8.966143
5,B07,Pos_Ctrl,10.0,392.0,294.0,1910.0,2055.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.750000,9.346476
6,B08,Pos_Ctrl,10.0,378.0,265.0,1798.0,2019.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.701058,8.736565
7,B09,Pos_Ctrl,10.0,401.0,293.0,1876.0,2048.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.730673,9.105627
8,C02,Cpd_001,0.1,415.0,37.0,315.0,2098.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.089157,1.111067
9,C03,Cpd_001,1.0,408.0,73.0,580.0,2087.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.178922,2.229715
10,C04,Cpd_001,10.0,399.0,219.0,1421.0,2071.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.548872,6.840027
11,D02,Cpd_002,0.1,422.0,34.0,308.0,2112.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080569,1.004045
12,D03,Cpd_002,1.0,410.0,37.0,312.0,2095.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090244,1.124617
13,D04,Cpd_002,10.0,418.0,42.0,319.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.100478,1.252159
14,E02,Cpd_003,0.1,412.0,41.0,320.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.099515,1.240147
15,E03,Cpd_003,1.0,405.0,142.0,890.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.350617,4.369381
17,F02,Cpd_004,0.1,418.0,29.0,301.0,2102.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.069378,0.864586
18,F03,Cpd_004,1.0,412.0,33.0,310.0,2096.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080097,0.998167
20,G02,Cpd_005,0.1,409.0,37.0,318.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090465,1.127366
21,G03,Cpd_005,1.0,415.0,50.0,402.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.120482,1.501442
22,G04,Cpd_005,10.0,407.0,61.0,489.0,2101.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.149877,1.867764
23,H02,Cpd_006,0.1,420.0,34.0,305.0,2097.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.080952,1.008826
24,H03,Cpd_006,1.0,416.0,33.0,309.0,2091.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.079327,0.988570
25,H04,Cpd_006,10.0,411.0,37.0,314.0,2085.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.090024,1.121880
26,I02,Cpd_007,0.1,418.0,46.0,340.0,2103.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.110048,1.371413
27,I03,Cpd_007,1.0,407.0,183.0,1102.0,2090.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.449631,5.603293
28,I04,Cpd_007,10.0,395.0,281.0,1798.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.711392,8.865349
29,J02,Cpd_008,0.1,412.0,37.0,311.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.089806,1.119157
30,J03,Cpd_008,1.0,408.0,41.0,338.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.100490,1.252306
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.822055,10.244425

In [36]:
potent_compound = df_clean["MBP_ratio_normalized"] > 10

df_clean[potent_compound]

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio,MBP_ratio_normalized
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.822055,10.244425

In [38]:
Compound_008 = df_clean["Compound"] == "Cpd_008"
df_clean[Compound_008]

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio,MBP_ratio_normalized
29,J02,Cpd_008,0.1,412.0,37.0,311.0,2094.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.089806,1.119157
30,J03,Cpd_008,1.0,408.0,41.0,338.0,2088.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.100490,1.252306
31,J04,Cpd_008,10.0,399.0,328.0,1956.0,2079.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.822055,10.244425

In [40]:
Compound_007 = df_clean["Compound"] == "Cpd_007"
df_clean[Compound_007]

,WellID,Compound,Dose_uM,TotalCells_Count,MBP_Positive_Count,Mean_MBP_Intensity_AU,Mean_DAPI_Intensity_AU,Plate_ID,Image_Date,Objective,Channel_MBP,Channel_DAPI,MBP_ratio,MBP_ratio_normalized
26,I02,Cpd_007,0.1,418.0,46.0,340.0,2103.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.110048,1.371413
27,I03,Cpd_007,1.0,407.0,183.0,1102.0,2090.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.449631,5.603293
28,I04,Cpd_007,10.0,395.0,281.0,1798.0,2078.0,Plate_01,2024-03-15,10x,CY3,DAPI,0.711392,8.865349